"use client";

import { useMemo, useState, useTransition } from "react";
import { Eye, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { deleteMasterData, saveMasterData, type MasterEntity } from "@/app/admin/master-data/actions";

export type Field = { key: string; label: string; type?: "text" | "number" | "date" | "textarea" | "select"; options?: { value: string; label: string }[]; table?: boolean };
export type MasterRecord = Record<string, string | number | null> & { id: string };

type Props = { entity: MasterEntity; singular: string; title: string; description: string; fields: Field[]; rows: MasterRecord[]; detailBasePath?: string };

const display = (value: string | number | null) => value === null || value === "" ? "—" : typeof value === "number" ? new Intl.NumberFormat("id-ID").format(value) : value;

export function MasterDataManager({ entity, singular, title, description, fields, rows, detailBasePath }: Props) {
  const [query, setQuery] = useState(""); const [editing, setEditing] = useState<MasterRecord | null | undefined>(); const [message, setMessage] = useState<string>(); const [isPending, startTransition] = useTransition();
  const filtered = useMemo(() => rows.filter(row => Object.values(row).some(value => String(value ?? "").toLowerCase().includes(query.toLowerCase()))), [rows, query]);
  const close = () => { setEditing(undefined); setMessage(undefined); };
  const submit = (form: HTMLFormElement) => { const raw = Object.fromEntries(new FormData(form)); startTransition(async () => { const result = await saveMasterData(entity, editing?.id ?? null, raw); if (result.error) setMessage(result.error); else close(); }); };
  const remove = (id: string) => { if (!window.confirm(`Hapus data ${singular.toLowerCase()} ini?`)) return; startTransition(async () => { const result = await deleteMasterData(entity, id); if (result.error) setMessage(result.error); }); };
  return <>
    <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="app-title-primary">{title}</h1><p className="mt-1 text-sm text-slate-500">{description}</p></div><button onClick={() => setEditing(null)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-brandHover"><Plus size={17} />Tambah {singular}</button></div>
    <section className="overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-apple-soft"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-semibold text-ink">{rows.length} data terdaftar</p><label className="flex w-full max-w-sm items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-slate-400 focus-within:border-brand/50 focus-within:bg-white"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder={`Cari ${singular.toLowerCase()}...`} className="w-full bg-transparent text-sm text-ink outline-none" /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{fields.filter(f => f.table !== false).map(f => <th key={f.key} className="px-5 py-3 font-semibold">{f.label}</th>)}<th className="px-5 py-3 text-right font-semibold">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(row => <tr key={row.id} className="transition hover:bg-slate-50/70">{fields.filter(f => f.table !== false).map(f => <td key={f.key} className="max-w-[220px] truncate px-5 py-4 text-slate-600">{f.key === "price" && row[f.key] !== null ? `Rp ${display(row[f.key])}` : display(row[f.key])}</td>)}<td className="px-5 py-4"><div className="flex justify-end gap-1">{detailBasePath && <a href={`${detailBasePath}/${row.id}`} className="rounded-lg p-2 text-slate-400 hover:bg-brand/10 hover:text-brand" aria-label="Detail"><Eye size={17}/></a>}<button onClick={() => setEditing(row)} className="rounded-lg p-2 text-slate-400 hover:bg-brand/10 hover:text-brand" aria-label="Edit"><Pencil size={17}/></button><button onClick={() => remove(row.id)} disabled={isPending} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-50" aria-label="Hapus"><Trash2 size={17}/></button></div></td></tr>)}{filtered.length === 0 && <tr><td colSpan={fields.filter(f => f.table !== false).length + 1} className="px-5 py-12 text-center text-slate-500">Belum ada data yang cocok.</td></tr>}</tbody></table></div></section>
    {editing !== undefined && <div className="fixed inset-0 z-30 flex items-end bg-slate-900/30 p-0 backdrop-blur-sm sm:items-center sm:justify-center sm:p-6"><form onSubmit={event => { event.preventDefault(); submit(event.currentTarget); }} className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:max-w-xl sm:rounded-3xl"><div className="mb-6 flex items-start justify-between"><div><h2 className="app-title-secondary">{editing ? `Edit ${singular}` : `Tambah ${singular}`}</h2><p className="mt-1 text-sm text-slate-500">Lengkapi data berikut dengan benar.</p></div><button type="button" onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={20}/></button></div>{message && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</p>}<div className="grid gap-4 sm:grid-cols-2">{fields.map(field => <label key={field.key} className={field.type === "textarea" ? "sm:col-span-2" : ""}><span className="mb-1.5 block text-sm font-medium text-slate-700">{field.label}</span>{field.type === "textarea" ? <textarea name={field.key} defaultValue={String(editing?.[field.key] ?? "")} className="min-h-24 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/10"/> : field.type === "select" ? <select name={field.key} defaultValue={String(editing?.[field.key] ?? "")} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/10"><option value="">Pilih {field.label}</option>{field.options?.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input name={field.key} type={field.type ?? "text"} defaultValue={String(editing?.[field.key] ?? "")} required={!["address", "description", "birth_date", "school_name", "grade", "parent_id", "package_id", "specialization"].includes(field.key)} step={field.key === "price" ? "0.01" : undefined} className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-brand focus:ring-2 focus:ring-brand/10"/>}</label>)}</div><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">Batal</button><button disabled={isPending} className="rounded-xl bg-brand px-5 py-2.5 text-sm font-semibold text-white hover:bg-brandHover disabled:opacity-60">{isPending ? "Menyimpan..." : "Simpan Data"}</button></div></form></div>}
  </>;
}
